### ISSUE TITLE
Scroll position probleme when no more message are added

### ISSUE THREAD

**Issue by Qypol342** [BlaBl-App/BlaBl-App#16]
Hi 
there a small bug, when you pull to load more message, the app scroll a bit lower werdly, about 4 or 5 messages.
this bug only appear when there are no more message to be loaded.

the expected out reponse from the app is simple it should do nothing, it shoudl scroll down

thanks, you can ask me for more infromation on the bug

**Comment by nabilesall** [comment]
Done !
